[build]
  command = "npm run build"
  publish = "out"

[context.production.environment]
  NEXT_SERVERLESS = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
