[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  NEXT_SERVERLESS = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[plugins]]
package = "@netlify/plugin-nextjs"
